el = new Cube 300, 200, 50

el.resetMovement()
el.movement()
el.moveTo(x, y, z)
el.moveXTo(x)
el.moveYTo(y)
el.moveZTo(z)
el.move(x, y, z)
el.moveX(x)
el.moveY(y)
el.moveZ(z)
el.resetScale()
el.getScale()
el.scaleTo(x, y, z)
el.scaleXTo(x)
el.scaleYTo(y)
el.scaleZTo(z)
el.scale(x, y, z)
el.scaleAllTo(x)
el.scaleX(x)
el.scaleY(y)
el.scaleZ(z)
el.reperspective()
el.perspective(d)
el.resetRotation()
el.rotation()
el.rotateTo(x, y, z)
el.rotateXTo(x)
el.rotateYTo(y)
el.rotateZTo(z)
el.rotate(x, y, z)
el.rotateX(x)
el.rotateY(y)
el.rotateZ(z)
el.resetLocalMovement()
el.localMovement()
el.localMoveTo(x, y, z)
el.localMoveXTo(x)
el.localMoveYTo(y)
el.localMoveZTo(z)
el.localMove(x, y, z)
el.localMoveX(x)
el.localMoveY(y)
el.localMoveZ(z)
el.resetLocalRotation()
el.localRotation()
el.localRotateTo(x, y, z)
el.localRotateXTo(x)
el.localRotateYTo(y)
el.localRotateZTo(z)
el.localRotate(x, y, z)
el.localRotateX(x)
el.localRotateY(y)
el.localRotateZ(z)

el.setOrigin(x, y, z)